LIBS = -std=c++11

all: ArrayLinearList ArrayLinearListImproved Chain CircularWithHeader

ArrayLinearList:
	g++ Implementation/ArrayLinearList.cpp -o exe/ArrayLinearList $(LIBS)

ArrayLinearListImproved:
	g++ Implementation/ArrayLinearListImproved.cpp -o exe/ArrayLinearListImproved $(LIBS)

ArrayStack:
	g++ Implementation/ArrayStack.cpp -o exe/ArrayStack $(LIBS)

ArrayQueue:
	g++ Implementation/ArrayQueue.cpp -o exe/ArrayQueue $(LIBS)

Chain:
	g++ Implementation/Chain.cpp -o exe/Chain $(LIBS)

CircularWithHeader:
	g++ Implementation/CircularWithHeader.cpp -o exe/CircularWithHeader $(LIBS)

LinkedStack:
	g++ Implementation/LinkedStack.cpp -o exe/LinkedStack $(LIBS)
